apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: mysql
  namespace: default
spec:
  components:
    - name: db-operator
      type: helm
      properties:
        repoType: helm
        url: https://presslabs.github.io/charts
        chart: db-operator
        version: "v0.7.0"
    - name: mysql-cluster
      type: raw
      dependsOn:
        - db-operator
      properties:
        apiVersion: mysql.presslabs.org/v1alpha1
        kind: MysqlCluster
        metadata:
          name: mysql-cluster
        spec:
          replicas: 1
          secretName: mysql-secret
